import type {Ability,Character,Creature,DamageType,ImportedFeatureRule} from './types.js';

export const RULES_VERSION={
  label:'2024 Revised Fifth Edition',srd:'5.2.1',errata:'SRD 5.2.1, including second-printing core-rule errata present at release',reviewed:'2026-08-13',
  officialSources:[
    'https://www.dndbeyond.com/srd',
    'https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf'
  ]
} as const;

const emptyDamage:DamageType[]=[];
const source=(anchor:string)=>({ruleset:'2024 SRD 5.2.1 (CC BY 4.0)',page:`Creature Stat Blocks — ${anchor}`,verified:'2026-08-13'});
const allSaves=(a:{str:number;dex:number;con:number;int:number;wis:number;cha:number})=>({...a});

export const CREATURES:Record<string,Creature>={
  cat:{id:'cat',name:'Cat',type:'Beast',cr:0,size:'Tiny',ac:12,hp:2,hitDice:'1d4',abilities:{str:3,dex:15,con:10,int:3,wis:12,cha:7},saves:allSaves({str:-4,dex:4,con:0,int:-4,wis:1,cha:-2}),skills:{Perception:3,Stealth:4},speeds:{walk:40,climb:40},senses:['Darkvision 60 ft.','Passive Perception 13'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Jumper',summary:'Jump distance uses Dexterity rather than Strength.'}],actions:[{id:'scratch',name:'Scratch',type:'attack',cost:'action',attackBonus:4,ability:'dex',kind:'beast',reach:5,damage:[{expression:'1',type:'Slashing'}]}],artKey:'cat',source:source('Cat')},
  'constrictor-snake':{id:'constrictor-snake',name:'Constrictor Snake',type:'Beast',cr:.25,size:'Large',ac:13,hp:13,hitDice:'2d10+2',abilities:{str:15,dex:14,con:12,int:1,wis:10,cha:3},saves:allSaves({str:2,dex:2,con:1,int:-5,wis:0,cha:-4}),skills:{Perception:2,Stealth:4},speeds:{walk:30,swim:30},senses:['Blindsight 10 ft.','Passive Perception 12'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:4,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d8+2',type:'Piercing'}]},{id:'constrict',name:'Constrict',type:'save',cost:'action',saveAbility:'str',dc:12,range:'5 ft.',damageOnFail:[{expression:'3d4',type:'Bludgeoning'}],effectsOnFail:[{condition:'Grappled',escapeDc:12,targetSizeMax:'Medium'}]}],artKey:'snake',source:source('Constrictor Snake')},
  panther:{id:'panther',name:'Panther',type:'Beast',cr:.25,size:'Medium',ac:13,hp:13,hitDice:'3d8',abilities:{str:14,dex:16,con:10,int:3,wis:14,cha:7},saves:allSaves({str:2,dex:3,con:0,int:-4,wis:2,cha:-2}),skills:{Perception:4,Stealth:7},speeds:{walk:50,climb:40},senses:['Darkvision 60 ft.','Passive Perception 14'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'rend',name:'Rend',type:'attack',cost:'action',attackBonus:5,ability:'dex',kind:'beast',reach:5,damage:[{expression:'1d6+3',type:'Slashing'}]},{id:'nimble-escape',name:'Nimble Escape',type:'automatic',cost:'bonus',prerequisite:'Choose Disengage or Hide.',notes:'The panther takes the Disengage or Hide action.'}],artKey:'cat',source:source('Panther')},
  'riding-horse':{id:'riding-horse',name:'Riding Horse',type:'Beast',cr:.25,size:'Large',ac:11,hp:13,hitDice:'2d10+2',abilities:{str:16,dex:13,con:12,int:2,wis:11,cha:7},saves:allSaves({str:3,dex:1,con:1,int:-4,wis:0,cha:-2}),skills:{},speeds:{walk:60},senses:['Passive Perception 10'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'hooves',name:'Hooves',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d8+3',type:'Bludgeoning'}]}],artKey:'horse',source:source('Riding Horse')},
  'giant-bat':{id:'giant-bat',name:'Giant Bat',type:'Beast',cr:.25,size:'Large',ac:13,hp:22,hitDice:'4d10',abilities:{str:15,dex:16,con:11,int:2,wis:12,cha:6},saves:allSaves({str:2,dex:3,con:0,int:-4,wis:1,cha:-2}),skills:{},speeds:{walk:10,fly:60},senses:['Blindsight 120 ft.','Passive Perception 11'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:5,ability:'dex',kind:'beast',reach:5,damage:[{expression:'1d6+3',type:'Piercing'}]}],artKey:'bat',source:source('Giant Bat')},
  'black-bear':{id:'black-bear',name:'Black Bear',type:'Beast',cr:.5,size:'Medium',ac:11,hp:19,hitDice:'3d8+6',abilities:{str:15,dex:12,con:14,int:2,wis:12,cha:7},saves:allSaves({str:2,dex:1,con:2,int:-4,wis:1,cha:-2}),skills:{Perception:5},speeds:{walk:30,climb:30,swim:30},senses:['Darkvision 60 ft.','Passive Perception 15'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'multiattack',name:'Multiattack',type:'multiattack',cost:'action',sequence:['rend','rend']},{id:'rend',name:'Rend',type:'attack',cost:'action',attackBonus:4,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d6+2',type:'Slashing'}]}],artKey:'bear',source:source('Black Bear')},
  'giant-goat':{id:'giant-goat',name:'Giant Goat',type:'Beast',cr:.5,size:'Large',ac:11,hp:19,hitDice:'3d10+3',abilities:{str:17,dex:13,con:12,int:3,wis:12,cha:6},saves:allSaves({str:5,dex:1,con:1,int:-4,wis:1,cha:-2}),skills:{Perception:3},speeds:{walk:40,climb:30},senses:['Darkvision 60 ft.','Passive Perception 13'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'ram',name:'Ram',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d6+3',type:'Bludgeoning'}],riders:[{id:'charge',label:'Charge',prerequisite:'The goat moved at least 20 feet straight toward the target immediately before the hit.',damage:[{expression:'2d4',type:'Bludgeoning'}],effects:[{condition:'Prone',targetSizeMax:'Large'}]}],notes:'Select Charge only when its 20-foot straight-movement prerequisite is met.'}],artKey:'goat',source:source('Giant Goat')},
  'dire-wolf':{id:'dire-wolf',name:'Dire Wolf',type:'Beast',cr:1,size:'Large',ac:14,hp:22,hitDice:'3d10+6',abilities:{str:17,dex:15,con:15,int:3,wis:12,cha:7},saves:allSaves({str:3,dex:2,con:2,int:-4,wis:1,cha:-2}),skills:{Perception:5,Stealth:4},speeds:{walk:50},senses:['Darkvision 60 ft.','Passive Perception 15'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Pack Tactics',summary:'Advantage when an ally is within 5 feet of the target and not Incapacitated.'}],actions:[{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d10+3',type:'Piercing'}],effects:[{condition:'Prone',targetSizeMax:'Large'}]}],artKey:'wolf',source:source('Dire Wolf')},
  'brown-bear':{id:'brown-bear',name:'Brown Bear',type:'Beast',cr:1,size:'Large',ac:11,hp:22,hitDice:'3d10+6',abilities:{str:17,dex:12,con:15,int:2,wis:13,cha:7},saves:allSaves({str:3,dex:1,con:2,int:-4,wis:1,cha:-2}),skills:{Perception:3},speeds:{walk:40,climb:30},senses:['Darkvision 60 ft.','Passive Perception 13'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'multiattack',name:'Multiattack',type:'multiattack',cost:'action',sequence:['bite','claw']},{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d8+3',type:'Piercing'}]},{id:'claw',name:'Claw',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d4+3',type:'Slashing'}],effects:[{condition:'Prone',targetSizeMax:'Large'}]}],artKey:'bear',source:source('Brown Bear')},
  'giant-spider':{id:'giant-spider',name:'Giant Spider',type:'Beast',cr:1,size:'Large',ac:14,hp:26,hitDice:'4d10+4',abilities:{str:14,dex:16,con:12,int:2,wis:11,cha:4},saves:allSaves({str:2,dex:3,con:1,int:-4,wis:0,cha:-3}),skills:{Perception:4,Stealth:7},speeds:{walk:30,climb:30},senses:['Darkvision 60 ft.','Passive Perception 14'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Spider Climb',summary:'Climbs difficult surfaces and ceilings without an ability check.'},{name:'Web Walker',summary:'Ignores web movement restrictions and senses creatures on the same web.'}],actions:[{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:5,ability:'dex',kind:'beast',reach:5,damage:[{expression:'1d8+3',type:'Piercing'},{expression:'2d6',type:'Poison'}]},{id:'web',name:'Web',type:'save',cost:'action',saveAbility:'dex',dc:13,range:'60 ft.',effectsOnFail:[{condition:'Restrained',note:'Web object AC 10, HP 5, vulnerable to Fire, immune to Poison and Psychic.'}],recharge:{min:5,max:6}}],artKey:'spider',source:source('Giant Spider')},
  'giant-toad':{id:'giant-toad',name:'Giant Toad',type:'Beast',cr:1,size:'Large',ac:11,hp:39,hitDice:'6d10+6',abilities:{str:15,dex:13,con:13,int:2,wis:10,cha:3},saves:allSaves({str:2,dex:1,con:1,int:-4,wis:0,cha:-4}),skills:{},speeds:{walk:30,swim:30},senses:['Darkvision 60 ft.','Passive Perception 10'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Amphibious',summary:'Breathes air and water.'},{name:'Standing Leap',summary:'Long Jump 20 feet and High Jump 10 feet with or without a running start.'}],actions:[{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:4,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d6+2',type:'Piercing'},{expression:'2d4',type:'Poison'}],effects:[{condition:'Grappled',escapeDc:12,targetSizeMax:'Medium'}]},{id:'swallow',name:'Swallow',type:'automatic',cost:'action',prerequisite:'A Medium or smaller target grappled by Bite.',damage:[{expression:'3d6',type:'Acid'}],damageTiming:'At the end of each of the toad’s turns while a target is swallowed',effects:[{condition:'Blinded'},{condition:'Restrained'},{condition:'Total Cover'}],notes:'Bite is unavailable while a target is swallowed.'}],artKey:'toad',source:source('Giant Toad')},
  'giant-octopus':{id:'giant-octopus',name:'Giant Octopus',type:'Beast',cr:1,size:'Large',ac:11,hp:45,hitDice:'7d10+7',abilities:{str:17,dex:13,con:13,int:5,wis:10,cha:4},saves:allSaves({str:3,dex:1,con:1,int:-3,wis:0,cha:-3}),skills:{Perception:4,Stealth:5},speeds:{walk:10,swim:60},senses:['Darkvision 60 ft.','Passive Perception 14'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Water Breathing',summary:'Breathes only underwater and can hold its breath for 1 hour outside water.'}],actions:[{id:'tentacles',name:'Tentacles',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:10,damage:[{expression:'2d6+3',type:'Bludgeoning'}],effects:[{condition:'Grappled',escapeDc:13,targetSizeMax:'Medium'},{condition:'Restrained',targetSizeMax:'Medium'}]},{id:'ink-cloud',name:'Ink Cloud',type:'automatic',cost:'reaction',uses:{max:1,recovery:'long'},prerequisite:'After taking damage underwater.',notes:'Creates a heavily obscured 10-foot cube for 1 minute and permits movement up to Swim Speed.'}],artKey:'base',source:source('Giant Octopus')},
  lion:{id:'lion',name:'Lion',type:'Beast',cr:1,size:'Large',ac:12,hp:22,hitDice:'4d10',abilities:{str:17,dex:15,con:11,int:3,wis:12,cha:8},saves:allSaves({str:3,dex:2,con:0,int:-4,wis:1,cha:-1}),skills:{Perception:3,Stealth:4},speeds:{walk:50},senses:['Darkvision 60 ft.','Passive Perception 13'],resistances:[],immunities:[],vulnerabilities:[],traits:[{name:'Pack Tactics',summary:'Advantage when an ally is within 5 feet of the target and not Incapacitated.'},{name:'Running Leap',summary:'With a 10-foot running start, Long Jump up to 25 feet.'}],actions:[{id:'multiattack',name:'Multiattack',type:'multiattack',cost:'action',sequence:['rend','rend'],variants:[{id:'rend-roar',label:'Rend → Roar',sequence:['rend','roar']},{id:'roar-rend',label:'Roar → Rend',sequence:['roar','rend']}],notes:'Make two Rend attacks, or replace one Rend with Roar.'},{id:'rend',name:'Rend',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d8+3',type:'Slashing'}]},{id:'roar',name:'Roar',type:'save',cost:'action',saveAbility:'wis',dc:11,range:'15 ft.',effectsOnFail:[{condition:'Frightened',duration:'Until the start of the lion’s next turn'}]}],artKey:'cat',source:source('Lion')},
  tiger:{id:'tiger',name:'Tiger',type:'Beast',cr:1,size:'Large',ac:13,hp:30,hitDice:'4d10+8',abilities:{str:17,dex:16,con:14,int:3,wis:12,cha:8},saves:allSaves({str:3,dex:3,con:2,int:-4,wis:1,cha:-1}),skills:{Perception:3,Stealth:7},speeds:{walk:40},senses:['Darkvision 60 ft.','Passive Perception 13'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'rend',name:'Rend',type:'attack',cost:'action',attackBonus:5,ability:'str',kind:'beast',reach:5,damage:[{expression:'2d6+3',type:'Slashing'}],effects:[{condition:'Prone',targetSizeMax:'Large'}]},{id:'nimble-escape',name:'Nimble Escape',type:'automatic',cost:'bonus',prerequisite:'Choose Disengage or Hide.',notes:'The tiger takes the Disengage or Hide action.'}],artKey:'cat',source:source('Tiger')},
  'giant-constrictor-snake':{id:'giant-constrictor-snake',name:'Giant Constrictor Snake',type:'Beast',cr:2,size:'Huge',ac:12,hp:60,hitDice:'8d12+8',abilities:{str:19,dex:14,con:12,int:1,wis:10,cha:3},saves:allSaves({str:4,dex:2,con:1,int:-5,wis:0,cha:-4}),skills:{Perception:2},speeds:{walk:30,swim:30},senses:['Blindsight 10 ft.','Passive Perception 12'],resistances:[],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'multiattack',name:'Multiattack',type:'multiattack',cost:'action',sequence:['bite','constrict']},{id:'bite',name:'Bite',type:'attack',cost:'action',attackBonus:6,ability:'str',kind:'beast',reach:10,damage:[{expression:'2d6+4',type:'Piercing'}]},{id:'constrict',name:'Constrict',type:'save',cost:'action',saveAbility:'str',dc:14,range:'10 ft.',damageOnFail:[{expression:'2d8+4',type:'Bludgeoning'}],effectsOnFail:[{condition:'Grappled',escapeDc:14,targetSizeMax:'Large'}]}],artKey:'snake',source:source('Giant Constrictor Snake')},
  'polar-bear':{id:'polar-bear',name:'Polar Bear',type:'Beast',cr:2,size:'Large',ac:12,hp:42,hitDice:'5d10+15',abilities:{str:20,dex:14,con:16,int:2,wis:13,cha:7},saves:allSaves({str:5,dex:2,con:3,int:-4,wis:1,cha:-2}),skills:{Perception:5,Stealth:4},speeds:{walk:40,swim:40},senses:['Darkvision 60 ft.','Passive Perception 15'],resistances:['Cold'],immunities:[],vulnerabilities:[],traits:[],actions:[{id:'multiattack',name:'Multiattack',type:'multiattack',cost:'action',sequence:['rend','rend']},{id:'rend',name:'Rend',type:'attack',cost:'action',attackBonus:7,ability:'str',kind:'beast',reach:5,damage:[{expression:'1d8+5',type:'Slashing'}]}],artKey:'bear',source:source('Polar Bear')}
};

export const SKILL_ABILITIES:Record<string,Ability>={Acrobatics:'dex','Animal Handling':'wis',Arcana:'int',Athletics:'str',Deception:'cha',History:'int',Insight:'wis',Intimidation:'cha',Investigation:'int',Medicine:'wis',Nature:'int',Perception:'wis',Performance:'cha',Persuasion:'cha',Religion:'int','Sleight of Hand':'dex',Stealth:'dex',Survival:'wis'};

export const MOON_FORM_SPELL_LEVELS:Record<string,number>={'Starry Wisp':3,'Cure Wounds':3,'Moonbeam':3,'Conjure Animals':5,'Fount of Moonlight':7,'Mass Cure Wounds':9};

export const CLASS_FEATURES:Record<string,ImportedFeatureRule[]>={
  Barbarian:[
    {id:'rage',name:'Rage',source:'Barbarian',level:1,summary:'Bonus Action. B/P/S resistance; Advantage on Strength checks and saves; no spells or Concentration.',activation:'bonus',retention:{wildshape:true},grants:{resistances:['Bludgeoning','Piercing','Slashing']}},
    {id:'barbarian-unarmored-defense',name:'Unarmored Defense',source:'Barbarian',level:1,summary:'AC 10 + Dexterity + Constitution while not wearing armor.',retention:{wildshape:true},requires:{noArmor:true},grants:{acFormula:{base:10,abilities:['dex','con']}}},
    {id:'danger-sense',name:'Danger Sense',source:'Barbarian',level:2,summary:'Advantage on eligible Dexterity saves while not Incapacitated.',retention:{wildshape:true}},
    {id:'reckless-attack',name:'Reckless Attack',source:'Barbarian',level:2,summary:'Choose on the first attack roll of the turn; Strength attack rolls gain Advantage until next turn, and attacks against you gain Advantage.',retention:{wildshape:true}},
    {id:'extra-attack-barbarian',name:'Extra Attack',source:'Barbarian',level:5,summary:'Two attacks whenever you take the Attack action; does not combine with Multiattack.',retention:{wildshape:true}},
    {id:'fast-movement',name:'Fast Movement',source:'Barbarian',level:5,summary:'+10 Speed while not wearing Heavy armor.',retention:{wildshape:true},grants:{speedBonus:10}},
    {id:'relentless-rage',name:'Relentless Rage',source:'Barbarian',level:11,summary:'At 0 HP while Raging, make a Constitution save to remain conscious.',retention:{wildshape:true}}
  ],
  Bard:[{id:'bardic-inspiration',name:'Bardic Inspiration',source:'Bard',level:1,summary:'Bonus Action; requires a target that can see or hear you.',activation:'bonus',retention:{wildshape:true}},{id:'jack-of-all-trades',name:'Jack of All Trades',source:'Bard',level:2,summary:'Applies to eligible ability checks lacking proficiency.',retention:{wildshape:true}},{id:'expertise-bard',name:'Expertise',source:'Bard',level:2,summary:'Retained through skill proficiency rules.',retention:{wildshape:true}}],
  Cleric:[{id:'channel-divinity',name:'Channel Divinity',source:'Cleric',level:2,summary:'Class feature remains, but individual options may require a Holy Symbol or Magic action.',retention:{wildshape:true}},{id:'blessed-strikes',name:'Blessed Strikes',source:'Cleric',level:7,summary:'Requires the selected option’s weapon or cantrip trigger.',retention:{wildshape:true}}],
  Druid:[{id:'wild-shape',name:'Wild Shape',source:'Druid',level:2,summary:'Bonus Action transformation into a known legal Beast form.'},{id:'wild-resurgence',name:'Wild Resurgence',source:'Druid',level:5,summary:'Can exchange spell slots and Wild Shape uses as specified by the feature.',retention:{wildshape:true}},{id:'elemental-fury',name:'Elemental Fury',source:'Druid',level:7,summary:'Primal Strike can add elemental damage once per turn to a weapon or Beast-form attack.',retention:{wildshape:true}},{id:'beast-spells',name:'Beast Spells',source:'Druid',level:18,summary:'Allows spells in Wild Shape except costly or consumed Material components.',retention:{wildshape:true}}],
  Fighter:[{id:'second-wind',name:'Second Wind',source:'Fighter',level:1,summary:'Bonus Action healing; uses a tracked resource.',activation:'bonus',retention:{wildshape:true}},{id:'action-surge',name:'Action Surge',source:'Fighter',level:2,summary:'One additional action on your turn, except the Magic action.',retention:{wildshape:true}},{id:'extra-attack-fighter',name:'Extra Attack',source:'Fighter',level:5,summary:'Changes the Attack action; it does not add attacks to a creature’s Multiattack action.',retention:{wildshape:true}},{id:'indomitable',name:'Indomitable',source:'Fighter',level:9,summary:'Reroll a failed saving throw with a Fighter-level bonus.',retention:{wildshape:true}}],
  Monk:[{id:'martial-arts',name:'Martial Arts',source:'Monk',level:1,summary:'Applies to Unarmed Strikes and Monk weapons, not automatically to Beast attacks.',retention:{wildshape:true},requires:{noArmor:true,noShield:true}},{id:'monk-unarmored-defense',name:'Unarmored Defense',source:'Monk',level:1,summary:'AC 10 + Dexterity + Wisdom while not wearing armor or a Shield.',retention:{wildshape:true},requires:{noArmor:true,noShield:true},grants:{acFormula:{base:10,abilities:['dex','wis']}}},{id:'monk-focus',name:'Monk’s Focus',source:'Monk',level:2,summary:'Focus Points and Focus actions remain available when their anatomy/action requirements are met.',retention:{wildshape:true}},{id:'unarmored-movement',name:'Unarmored Movement',source:'Monk',level:2,summary:'Speed bonus while not wearing armor or a Shield.',retention:{wildshape:true}},{id:'deflect-attacks',name:'Deflect Attacks',source:'Monk',level:3,summary:'Reaction to reduce B/P/S damage from an attack roll.',retention:{wildshape:true}},{id:'extra-attack-monk',name:'Extra Attack',source:'Monk',level:5,summary:'Changes the Attack action; does not combine with Multiattack.',retention:{wildshape:true}},{id:'evasion-monk',name:'Evasion',source:'Monk',level:7,summary:'Applies to qualifying Dexterity saves.',retention:{wildshape:true}}],
  Paladin:[{id:'lay-on-hands',name:'Lay On Hands',source:'Paladin',level:1,summary:'Bonus Action touch healing from a tracked pool.',activation:'bonus',retention:{wildshape:true}},{id:'channel-divinity-paladin',name:'Channel Divinity',source:'Paladin',level:3,summary:'Individual options may require a weapon, Holy Symbol, or spellcasting-like prerequisites.',retention:{wildshape:true}},{id:'extra-attack-paladin',name:'Extra Attack',source:'Paladin',level:5,summary:'Two attacks whenever you take the Attack action; does not combine with Multiattack.',retention:{wildshape:true}},{id:'aura-of-protection',name:'Aura of Protection',source:'Paladin',level:6,summary:'Adds Charisma modifier to saves while not Incapacitated.',retention:{wildshape:true}},{id:'radiant-strikes',name:'Radiant Strikes',source:'Paladin',level:11,summary:'Requires a melee weapon or Unarmed Strike; Beast attacks do not automatically qualify.',retention:{wildshape:true}}],
  Ranger:[{id:'favored-enemy',name:'Favored Enemy / Hunter’s Mark',source:'Ranger',level:1,summary:'An already-active Hunter’s Mark can continue through Wild Shape while Concentration continues.',retention:{wildshape:true}},{id:'extra-attack-ranger',name:'Extra Attack',source:'Ranger',level:5,summary:'Two attacks whenever you take the Attack action; does not combine with Multiattack.',retention:{wildshape:true}},{id:'roving',name:'Roving',source:'Ranger',level:6,summary:'+10 Speed and Climb/Swim equal to Speed while not wearing Heavy armor.',retention:{wildshape:true},grants:{speedBonus:10}},{id:'tireless',name:'Tireless',source:'Ranger',level:10,summary:'Magic action Temporary HP; new Temporary HP does not stack.',retention:{wildshape:true}},{id:'natures-veil',name:'Nature’s Veil',source:'Ranger',level:14,summary:'Bonus Action invisibility using a tracked resource.',activation:'bonus',retention:{wildshape:true}},{id:'feral-senses',name:'Feral Senses',source:'Ranger',level:18,summary:'Adds Blindsight 30 feet.',retention:{wildshape:true}}],
  Rogue:[{id:'sneak-attack',name:'Sneak Attack',source:'Rogue',level:1,summary:'Requires a Finesse or Ranged weapon; ordinary Beast attacks do not qualify.',retention:{wildshape:true}},{id:'cunning-action',name:'Cunning Action',source:'Rogue',level:2,summary:'Bonus Action Dash, Disengage, or Hide.',activation:'bonus',retention:{wildshape:true}},{id:'uncanny-dodge',name:'Uncanny Dodge',source:'Rogue',level:5,summary:'Reaction against a visible attacker that hits.',retention:{wildshape:true}},{id:'evasion-rogue',name:'Evasion',source:'Rogue',level:7,summary:'Applies to qualifying Dexterity saves.',retention:{wildshape:true}},{id:'reliable-talent',name:'Reliable Talent',source:'Rogue',level:7,summary:'Applies to checks using a retained proficiency.',retention:{wildshape:true}}],
  Sorcerer:[{id:'innate-sorcery',name:'Innate Sorcery',source:'Sorcerer',level:1,summary:'Retained, but its benefits affect spells and are inactive while spellcasting is blocked.',retention:{wildshape:true},requires:{spellcasting:true}},{id:'metamagic',name:'Metamagic',source:'Sorcerer',level:2,summary:'Available only when the current form permits spellcasting.',retention:{wildshape:true},requires:{spellcasting:true}}],
  Warlock:[{id:'pact-magic',name:'Pact Magic',source:'Warlock',level:1,summary:'Ordinary Wild Shape blocks new spellcasting.',retention:{wildshape:true},requires:{spellcasting:true}},{id:'eldritch-invocations',name:'Eldritch Invocations',source:'Warlock',level:1,summary:'Each imported invocation is evaluated by its own prerequisites.',retention:{wildshape:true}},{id:'eldritch-mind',name:'Eldritch Mind',source:'Warlock',level:2,summary:'Advantage on Constitution saves to maintain Concentration.',retention:{wildshape:true}}],
  Wizard:[{id:'scholar',name:'Scholar',source:'Wizard',level:2,summary:'Relevant Expertise is retained through skill proficiency rules.',retention:{wildshape:true}},{id:'spellcasting-wizard',name:'Spellcasting',source:'Wizard',level:1,summary:'Ordinary Wild Shape blocks casting; Shapechange explicitly retains Spellcasting.',retention:{shapechange:true},requires:{spellcasting:true}}]
};

export const SUBCLASS_FEATURES:Record<string,ImportedFeatureRule[]>={
  'Path of the Berserker':[
    {id:'berserker-frenzy',name:'Frenzy',source:'Path of the Berserker',level:3,automation:'conditional',summary:'The first eligible Strength hit after using Reckless Attack while Raging can deal extra d6s equal to the Rage Damage bonus.',retention:{wildshape:true},requires:{strengthAttack:true}},
    {id:'mindless-rage',name:'Mindless Rage',source:'Path of the Berserker',level:6,automation:'calculated',summary:'While Raging, Charmed and Frightened are removed and cannot affect you.',retention:{wildshape:true}},
    {id:'berserker-retaliation',name:'Retaliation',source:'Path of the Berserker',level:10,automation:'conditional',summary:'After nearby creature damage, a Reaction can make one melee weapon or Unarmed Strike attack.',retention:{wildshape:true}},
    {id:'intimidating-presence',name:'Intimidating Presence',source:'Path of the Berserker',level:14,automation:'conditional',summary:'Bonus Action Wisdom-save fear effect with a Long Rest use and Rage-use recharge option.',retention:{wildshape:true},activation:'bonus'}
  ],
  'College of Lore':[
    {id:'cutting-words',name:'Cutting Words',source:'College of Lore',level:3,automation:'conditional',summary:'Reaction Bardic Inspiration reduction after a visible creature succeeds on an eligible roll.',retention:{wildshape:true},requires:{speech:true}},
    {id:'magical-discoveries',name:'Magical Discoveries',source:'College of Lore',level:6,automation:'reference',summary:'Selected spells must be present in the imported spell list.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'peerless-skill',name:'Peerless Skill',source:'College of Lore',level:14,automation:'conditional',summary:'Can add Bardic Inspiration to a failed ability check, spending the use only if the check succeeds.',retention:{wildshape:true}}
  ],
  'Life Domain':[
    {id:'disciple-of-life',name:'Disciple of Life',source:'Life Domain',level:3,automation:'conditional',summary:'Adds healing when an eligible spell restores Hit Points; imported spell and target details determine the result.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'preserve-life',name:'Preserve Life',source:'Life Domain',level:3,automation:'conditional',summary:'Channel Divinity healing is target- and range-dependent.',retention:{wildshape:true}},
    {id:'supreme-healing',name:'Supreme Healing',source:'Life Domain',level:17,automation:'conditional',summary:'Eligible spell-healing dice use their maximum values.',retention:{wildshape:true},requires:{spellcasting:true}}
  ],
  'Circle of the Land':[
    {id:'land-circle-spells',name:'Circle Spells',source:'Circle of the Land',level:3,automation:'reference',summary:'Always-prepared land spells must be present on the imported character.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'lands-aid',name:"Land's Aid",source:'Circle of the Land',level:3,automation:'conditional',summary:'Magic Action expends Wild Shape for a Constitution-save area effect and healing.',retention:{wildshape:true},activation:'magic-action'},
    {id:'natural-recovery',name:'Natural Recovery',source:'Circle of the Land',level:6,automation:'reference',summary:'Spell-slot recovery choice is recorded from the source rather than guessed.',retention:{wildshape:true}},
    {id:'natures-ward',name:"Nature's Ward",source:'Circle of the Land',level:10,automation:'reference',summary:'The selected land grants a specific resistance or immunity that must be imported.',retention:{wildshape:true}}
  ],
  Champion:[
    {id:'improved-critical',name:'Improved Critical',source:'Champion',level:3,automation:'calculated',summary:'Weapon and Unarmed Strike attack rolls score critical hits on 19–20, expanding to 18–20 at Fighter level 15.',retention:{wildshape:true}},
    {id:'remarkable-athlete',name:'Remarkable Athlete',source:'Champion',level:3,automation:'calculated',summary:'Advantage on Initiative and eligible Strength (Athletics) checks.',retention:{wildshape:true}},
    {id:'additional-fighting-style',name:'Additional Fighting Style',source:'Champion',level:7,automation:'reference',summary:'The selected Fighting Style must be present on the imported character.',retention:{wildshape:true}},
    {id:'heroic-warrior',name:'Heroic Warrior',source:'Champion',level:10,automation:'conditional',summary:'Heroic Inspiration is regained at the start of a turn when unavailable.',retention:{wildshape:true}},
    {id:'survivor',name:'Survivor',source:'Champion',level:18,automation:'conditional',summary:'Improves Death Saving Throws and restores HP at turn start while Bloodied and above 0 HP.',retention:{wildshape:true}}
  ],
  'Warrior of the Open Hand':[
    {id:'open-hand-technique',name:'Open Hand Technique',source:'Warrior of the Open Hand',level:3,automation:'conditional',summary:'Flurry of Blows hits can Addle, Push, or Topple after their target prerequisites.',retention:{wildshape:true}},
    {id:'wholeness-of-body',name:'Wholeness of Body',source:'Warrior of the Open Hand',level:6,automation:'conditional',summary:'Bonus Action self-healing with limited uses.',retention:{wildshape:true},activation:'bonus'},
    {id:'fleet-step',name:'Fleet Step',source:'Warrior of the Open Hand',level:11,automation:'conditional',summary:'Step of the Wind can also provide its other option that turn.',retention:{wildshape:true}},
    {id:'quivering-palm',name:'Quivering Palm',source:'Warrior of the Open Hand',level:17,automation:'reference',summary:'Track the marked target and later save effect from the source.',retention:{wildshape:true}}
  ],
  'Oath of Devotion':[
    {id:'sacred-weapon',name:'Sacred Weapon',source:'Oath of Devotion',level:3,automation:'conditional',summary:'Channel Divinity empowers a selected weapon; ordinary Beast attacks are not weapons.',retention:{wildshape:true},requires:{weapon:true}},
    {id:'aura-of-devotion',name:'Aura of Devotion',source:'Oath of Devotion',level:7,automation:'conditional',summary:'Charmed immunity depends on the Paladin aura and range.',retention:{wildshape:true}},
    {id:'holy-nimbus',name:'Holy Nimbus',source:'Oath of Devotion',level:20,automation:'reference',summary:'The emanation, resistance, and action economy require an explicit active-effect record.',retention:{wildshape:true},activation:'bonus'}
  ],
  Hunter:[
    {id:'hunters-prey',name:"Hunter's Prey",source:'Hunter',level:3,automation:'conditional',summary:'The selected option changes eligible attacks and must be present in imported feature data.',retention:{wildshape:true}},
    {id:'hunters-lore',name:"Hunter's Lore",source:'Hunter',level:3,automation:'conditional',summary:"Reveals a marked target's damage immunities, resistances, and vulnerabilities.",retention:{wildshape:true},requires:{concentration:true}},
    {id:'defensive-tactics',name:'Defensive Tactics',source:'Hunter',level:7,automation:'reference',summary:'The selected defensive option must be imported.',retention:{wildshape:true}},
    {id:'superior-hunters-defense',name:"Superior Hunter's Defense",source:'Hunter',level:15,automation:'reference',summary:'The selected defensive option must be imported.',retention:{wildshape:true}}
  ],
  Thief:[
    {id:'fast-hands',name:'Fast Hands',source:'Thief',level:3,automation:'conditional',summary:'Cunning Action can make eligible Sleight of Hand checks or use objects with the Utilize action.',retention:{wildshape:true},activation:'bonus'},
    {id:'second-story-work',name:'Second-Story Work',source:'Thief',level:3,automation:'conditional',summary:'Climb Speed and jump benefits depend on current anatomy and Strength.',retention:{wildshape:true}},
    {id:'supreme-sneak',name:'Supreme Sneak',source:'Thief',level:9,automation:'conditional',summary:'Stealth Advantage applies while the movement limit is satisfied.',retention:{wildshape:true}},
    {id:'use-magic-device',name:'Use Magic Device',source:'Thief',level:13,automation:'reference',summary:'Attunement and charge-roll interactions require the imported item records.',retention:{wildshape:true}},
    {id:'thiefs-reflexes',name:"Thief's Reflexes",source:'Thief',level:17,automation:'reference',summary:'The extra first-round turn is shown as a reminder; Initiative order is not automatically rewritten.',retention:{wildshape:true}}
  ],
  'Draconic Sorcery':[
    {id:'draconic-resilience',name:'Draconic Resilience',source:'Draconic Sorcery',level:3,automation:'conditional',summary:'Base-form AC formula and HP increase depend on imported totals and armor state.',retention:{wildshape:true},requires:{noArmor:true}},
    {id:'elemental-affinity',name:'Elemental Affinity',source:'Draconic Sorcery',level:6,automation:'conditional',summary:'One eligible spell damage roll can add Charisma and optionally grant temporary resistance.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'dragon-wings',name:'Dragon Wings',source:'Draconic Sorcery',level:14,automation:'calculated',summary:'Bonus Action wings grant a Fly Speed equal to Speed; a spent use can be restored with 3 Sorcery Points.',retention:{wildshape:true},activation:'bonus'}
  ],
  'Fiend Patron':[
    {id:'dark-ones-blessing',name:"Dark One's Blessing",source:'Fiend Patron',level:3,automation:'conditional',summary:'Temporary HP trigger depends on a hostile creature reaching 0 HP near you.',retention:{wildshape:true}},
    {id:'dark-ones-own-luck',name:"Dark One's Own Luck",source:'Fiend Patron',level:6,automation:'conditional',summary:'Can add 1d10 after an ability check or save, subject to its use limit.',retention:{wildshape:true}},
    {id:'fiendish-resilience',name:'Fiendish Resilience',source:'Fiend Patron',level:10,automation:'reference',summary:'The chosen resistance must be imported as a structured feature.',retention:{wildshape:true}},
    {id:'hurl-through-hell',name:'Hurl Through Hell',source:'Fiend Patron',level:14,automation:'conditional',summary:'Once-per-rest hit rider requires target and damage resolution.',retention:{wildshape:true}}
  ],
  Evoker:[
    {id:'sculpt-spells',name:'Sculpt Spells',source:'Evoker',level:3,automation:'conditional',summary:'Chosen creatures can automatically succeed against eligible Evocation spells.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'potent-cantrip',name:'Potent Cantrip',source:'Evoker',level:6,automation:'conditional',summary:'Eligible damaging cantrips deal partial damage after their normal resolution.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'empowered-evocation',name:'Empowered Evocation',source:'Evoker',level:10,automation:'conditional',summary:'Adds Intelligence to one eligible Wizard Evocation spell damage roll.',retention:{wildshape:true},requires:{spellcasting:true}},
    {id:'overchannel',name:'Overchannel',source:'Evoker',level:14,automation:'reference',summary:'Maximum-damage uses and later self-damage require explicit per-rest tracking.',retention:{wildshape:true},requires:{spellcasting:true}}
  ]
};

export const SPECIES_FEATURES:Record<string,ImportedFeatureRule[]>={
  Aasimar:[{id:'celestial-revelation',name:'Celestial Revelation',source:'Aasimar',level:3,summary:'Species trait is not retained by Wild Shape, but an already-active timed effect can continue.',activation:'bonus'}],
  Dragonborn:[{id:'breath-weapon',name:'Breath Weapon',source:'Dragonborn',summary:'Species trait is not on Wild Shape’s retained list.'},{id:'draconic-flight',name:'Draconic Flight',source:'Dragonborn',level:5,summary:'An already-active duration can continue after a later transformation.',activation:'bonus'}],
  Dwarf:[{id:'dwarven-resilience',name:'Dwarven Resilience',source:'Dwarf',summary:'Species trait is not generally retained by Wild Shape.'}],
  Elf:[{id:'fey-ancestry',name:'Fey Ancestry',source:'Elf',summary:'Species trait is not generally retained by Wild Shape.'}],
  Gnome:[{id:'gnomish-cunning',name:'Gnomish Cunning',source:'Gnome',summary:'Species trait is not generally retained by Wild Shape.'}],
  Goliath:[{id:'large-form',name:'Large Form',source:'Goliath',level:5,summary:'An already-active timed effect can continue through a later transformation.',activation:'bonus'}],
  Halfling:[{id:'luck',name:'Luck',source:'Halfling',summary:'Species trait is not generally retained by Wild Shape.'}],
  Human:[{id:'versatile',name:'Versatile',source:'Human',summary:'The Origin feat is retained as a feat; other species traits are not generally retained.'}],
  Orc:[{id:'adrenaline-rush',name:'Adrenaline Rush',source:'Orc',summary:'Species trait is not generally available after Wild Shape; already-gained Temporary HP remains subject to normal Temporary HP rules.',activation:'bonus'}],
  Tiefling:[{id:'fiendish-legacy',name:'Fiendish Legacy',source:'Tiefling',summary:'An already-cast spell can continue; ordinary Wild Shape blocks new spellcasting.'}]
};

export function classLevel(character:Character,name:string):number{const target=name.trim().toLowerCase();return character.classes.find(c=>c.name.trim().toLowerCase()===target)?.level??0}
export function subclass(character:Character,name:string):string|null{const target=name.trim().toLowerCase();return character.classes.find(c=>c.name.trim().toLowerCase()===target)?.subclass??null}
